# Generated by Django 3.2.5 on 2022-02-14 20:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20220212_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listings',
            name='watchers',
            field=models.ManyToManyField(blank=True, related_name='all_watchers', to=settings.AUTH_USER_MODEL),
        ),
    ]
