# Generated by Django 3.2.5 on 2022-03-06 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_bids_buyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='buyer',
            field=models.ForeignKey(default='empty', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
